### ISSUE TITLE
Vite Issue

### ISSUE THREAD

**Issue by fnandesrafael** [mcnaveen/blurhash-from-url#27]
I'm trying to use the blurHashFromUrl in my React project, bootstrapped with Vite. I'm using TypeScript also. But every time I use the blurHashFromUrl, my navigator show me the following error:

![image](https://github.com/mcnaveen/blurhash-from-url/assets/48070538/7dd0138d-42c0-486c-9a75-b58f46ef31ce)

This is the code:

```ts
import React, { useState, useLayoutEffect } from 'react';
import { Blurhash } from 'react-blurhash';
import { blurhashFromURL } from 'blurhash-from-url';

type LazyImageProps = {
  src: string;
  alt: string;
  className: string;
};

export default function LazyImage({ src, alt, className }: LazyImageProps) {
  const [imageLoaded, setImageLoaded] = useState(false);
  const [hashedImage, setHashedImage] = useState('');

  useLayoutEffect(() => {
    const img = new Image();

    const hash = async () => {
      const result = await blurhashFromURL(src);
      setHashedImage(result.encoded);
    };

    hash();

    img.onload = () => setImageLoaded(true);
    img.src = src;
  }, [src]);

  return (
    <>
      {imageLoaded ? (
        <img src={src} alt={alt} loading="lazy" className={className} />
      ) : (
        <Blurhash
          hash={hashedImage}
          width={200}
          height={200}
          resolutionX={32}
          resolutionY={32}
          punch={1}
        />
      )}
    </>
  );
}
```

**Comment by mcnaveen** [comment]
Hi @fnandesrafael Thank you for using Blurhash from URL.

What you're trying to do is generate blurhash on the fly. Unfortunately, this is not possible right now because of the limitations of the dependencies.

But you can do this on the Server Side. Example: Nextjs API routes

**Comment by fnandesrafael** [comment]
> Hi @fnandesrafael Thank you for using Blurhash from URL.
> 
> What you're trying to do is generate blurhash on the fly. Unfortunately, this is not possible right now because of the limitations of the dependencies.
> 
> But you can do this on the Server Side. Example: Nextjs API routes

Oh! I see. Well, ty for the reply!
